/**
 * Runtime branding configuration
 * This file is generated by docker/init_react_envs.sh at container startup
 * and serves configuration from environment variables
 */

export const useBranding = async () => {
  try {
    const response = await fetch("/branding-config.json");
    if (response.ok) {
      return await response.json();
    }
  } catch (error) {
    console.warn("Failed to load branding config:", error);
  }

  // Fallback defaults
  return {
    APP_NAME: "NetBird Dashboard",
    APP_LOGO_FULL: "/assets/netbird-full.svg",
    APP_LOGO_MARK: "/assets/netbird.svg",
  };
};
